plugins/redmine_dmsf/config/routes.rb
# encoding: utf-8
# frozen_string_literal: true
#
# Redmine plugin for Document Management System "Features"
#
# Copyright © 2011    Vít Jonáš <vit.jonas@gmail.com>
# Copyright © 2012    Daniel Munn <dan.munn@munnster.co.uk>
# Copyright © 2011-22 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


if Redmine::Plugin.installed? :redmine_dmsf
  RedmineApp::Application.routes.draw do

    #
    # dmsf controller
    #   /projects/<project>/dmsf
    #   [As this controller also processes 'folders' it maybe better to branch into a folder route rather than leaving it as is]
    ##
    post '/projects/:id/dmsf/create', controller: 'dmsf', action: 'create'
    get '/projects/:id/dmsf/notify/activate', controller: 'dmsf', action: 'notify_activate', as: 'notify_activate_dmsf'
    get '/projects/:id/dmsf/notify/deactivate', controller: 'dmsf', action: 'notify_deactivate', as: 'notify_deactivate_dmsf'
    delete '/projects/:id/dmsf/delete', controller: 'dmsf', action: 'delete', as: 'delete_dmsf'
    post '/projects/:id/dmsf/save', controller: 'dmsf', action: 'save'
    post '/projects/:id/dmsf/save/root', controller: 'dmsf', action: 'save_root'
    post '/projects/dmsf/entries', controller: 'dmsf', action: 'entries_operation', as: 'entries_operations_dmsf'
    post '/projects/:id/dmsf/tag_changed', controller: 'dmsf', action: 'tag_changed', as: 'tag_changed'
    post '/projects/:id/dmsf/entries/delete', controller: 'dmsf', action: 'delete_entries', as: 'delete_entries'
    post '/projects/:id/dmsf/entries/email', to: 'dmsf#entries_email', as: 'email_entries'
    get '/projects/:id/dmsf/entries/download_email_entries', controller: 'dmsf', action: 'download_email_entries', as: 'download_email_entries'
    get '/projects/:id/dmsf/lock', controller: 'dmsf', action: 'lock', as: 'lock_dmsf'
    get '/projects/:id/dmsf/unlock', controller: 'dmsf', action: 'unlock', as: 'unlock_dmsf'
    get '/projects/:id/dmsf/', controller: 'dmsf', action: 'show', as: 'dmsf_folder'
    get '/projects/:id/dmsf/new', controller: 'dmsf', action: 'new', as: 'new_dmsf'
    get '/projects/:id/dmsf/edit', controller: 'dmsf', action: 'edit', as: 'edit_dmsf'
    get '/projects/:id/dmsf/edit/root', controller: 'dmsf', action: 'edit_root', as: 'edit_root_dmsf'
    get '/projects/:id/dmsf/trash', controller: 'dmsf', action: 'trash', as: 'trash_dmsf'
    get '/projects/:id/dmsf/restore', controller: 'dmsf', action: 'restore', as: 'restore_dmsf'
    post '/projects/dmsf/expand_folder', controller: 'dmsf', action: 'expand_folder', as: 'expand_folder_dmsf'
    get '/projects/dmsf/add_email', to: 'dmsf#add_email', as: 'add_email_dmsf'
    post '/projects/dmsf/append_email', to: 'dmsf#append_email', as: 'append_email_dmsf'
    get '/projects/dmsf/autocomplete_for_user', to: 'dmsf#autocomplete_for_user'
    put '/projects/:id/dmsf', controller: 'dmsf', action: 'drop'
    get '/projects/:id/dmsf/empty_trash', to: 'dmsf#empty_trash', as: 'empty_trash'
    get '/dmsf', to: 'dmsf#index', as: 'dmsf_index'

    # dmsf_context_menu_controller
    match '/projects/dmsf/context_menu', to: 'dmsf_context_menus#dmsf', as: 'dmsf_context_menu', via: [:get, :post]
    match '/projects/:id/dmsf/trash/context_menu', to: 'dmsf_context_menus#trash', as: 'dmsf_trash_context_menu', via: [:get, :post]

    #
    # dmsf_state controller
    #   /projects/<project>/dmsf/state
    ##
    post '/projects/:id/dmsf/state', controller: 'dmsf_state', action: 'user_pref_save', as: 'dmsf_user_pref_save'

    #
    #  dmsf_upload controller
    #   /projects/<project>/dmsf/upload - dmsf_upload controller
    ##

    get '/projects/:id/dmsf/upload/multi_upload', controller: 'dmsf_upload', action: 'multi_upload', as: 'multi_dmsf_upload'
    post '/projects/:id/dmsf/upload/files', controller: 'dmsf_upload', action: 'upload_files'
    get '/projects/:id/dmsf/upload/files', controller: 'dmsf_upload', action: 'upload_files'
    post '/projects/:id/dmsf/upload', controller: 'dmsf_upload', action: 'upload'
    post '/projects/:id/dmsf/upload/commit', controller: 'dmsf_upload', action: 'commit_files'
    post '/projects/:id/dmsf/commit', controller: 'dmsf_upload', action: 'commit'
    match 'dmsf_uploads', to: 'dmsf_upload#upload', via: :post
    delete '/dmsf/attachments/:id/delete', to: 'dmsf_upload#delete_dmsf_attachment', as: 'dmsf_attachment'
    delete '/dmsf/link_attachments/:id/delete', to: 'dmsf_upload#delete_dmsf_link_attachment', as: 'dmsf_link_attachment'

    #
    # dmsf_links controller
    #   /dmsf/links/<file id>
    ##
    get '/dmsf/links/:id/restore', controller: 'dmsf_links', action: 'restore', as: 'restore_dmsf_link'
    delete '/dmsf/links/:id', controller: 'dmsf_links', action: 'delete'

    # Just to keep backward compatibility with old external direct links
    get '/dmsf_files/:id', controller: 'dmsf_files', action: 'show'
    get '/dmsf_files/:id/download', controller: 'dmsf_files', action: 'show', download: ''

    #
    # files_copy controller
    #   /dmsf/files/<file id>/copy
    ##
    post '/dmsf/files/:id/copy/copy', controller: 'dmsf_files_copy', action: 'copy'
    post '/dmsf/files/:id/copy/move', controller: 'dmsf_files_copy', action: 'move'
    get '/dmsf/files/:id/copy', controller: 'dmsf_files_copy', action: 'new', as: 'copy_file'

    #
    # folders_copy controller
    #   /dmsf/folders/<folder id>/copy
    ##
    post '/dmsf/folders/:id/copy/copy', controller: 'dmsf_folders_copy', action: 'copy'
    post '/dmsf/folders/:id/copy/move', controller: 'dmsf_folders_copy', action: 'move'
    get '/dmsf/folders/:id/copy', controller: 'dmsf_folders_copy', action: 'new', as: 'copy_folder'

    #
    # dmsf_files controller
    #   /dmsf/files/<file id>
    ##
    get '/dmsf/files/:id/notify/activate', controller: 'dmsf_files', action: 'notify_activate', as: 'notify_activate_dmsf_files'
    get '/dmsf/files/:id/notify/deactivate', controller: 'dmsf_files', action: 'notify_deactivate', as: 'notify_deactivate_dmsf_files'
    get '/dmsf/files/:id/lock', controller: 'dmsf_files', action: 'lock', as: 'lock_dmsf_files'
    get '/dmsf/files/:id/unlock', controller: 'dmsf_files', action: 'unlock', as: 'unlock_dmsf_files'
    post '/dmsf/files/:id/delete', controller: 'dmsf_files', action: 'delete', as: 'delete_dmsf_files'
    post '/dmsf/files/:id/revision/create', controller: 'dmsf_files', action: 'create_revision'
    get '/dmsf/files/:id/revision/delete', controller: 'dmsf_files', action: 'delete_revision', as: 'delete_revision'
    get '/dmsf/files/:id/revision/obsolete', controller: 'dmsf_files', action: 'obsolete_revision', as: 'obsolete_revision'
    get '/dmsf/files/:id/download', to: 'dmsf_files#view', download: '', as: 'download_dmsf_file' # Otherwise will not route nil into the download param
    get '/dmsf/files/:id/view', to: 'dmsf_files#view', as: 'view_dmsf_file'
    get '/dmsf/files/:id', controller: 'dmsf_files', action: 'show', as: 'dmsf_file'
    delete '/dmsf/files/:id', controller: 'dmsf_files', action: 'delete'
    get '/dmsf/files/:id/restore', controller: 'dmsf_files', action: 'restore', as: 'restore_dmsf_file'
    get '/dmsf/files/:id/thumbnail', to: 'dmsf_files#thumbnail', as: 'dmsf_thumbnail'
    get '/dmsf/files/:id/:filename', to: 'dmsf_files#view', :id => /\d+/, :filename => /.*/, as: 'static_dmsf_file'

    # Approval workflow
    resources :dmsf_workflows do
      member do
        get 'autocomplete_for_user'
        get 'action'
        get 'assign'
        get 'log'
        post 'new_action'
        get 'start'
        post 'assignment'
        get 'new_step'
        put 'update_step'
        delete 'delete_step'
      end
    end

    match 'dmsf_workflows/:id/edit', controller: 'dmsf_workflows', action: 'add_step', id: /\d+/, via: :post
    match 'dmsf_workflows/:id/edit', controller: 'dmsf_workflows', action: 'remove_step', id: /\d+/, via: :delete
    match 'dmsf_workflows/:id/edit', controller: 'dmsf_workflows', action: 'reorder_steps', id: /\d+/, via: :put

    # Links
    resources :dmsf_links do
      member do
        get 'restore'
        get 'autocomplete_for_project'
        get 'autocomplete_for_folder'
      end
    end

    # Public URLs
    resource :dmsf_public_urls

     # Folder permissions
    resource :dmsf_folder_permissions do
      member do
        get 'autocomplete_for_user'
        post 'append'
      end
    end

    # WebDAV workaround for clients checking WebDAV availability in the root
    unless Redmine::Plugin.installed?(:easy_extensions)
      match '/', to: lambda { |env| [405, {}, [env.to_s]] }, via: [:propfind, :options]
    end
    match '/dmsf', to: lambda { |env| [405, {}, [env.to_s]] }, via: [:propfind, :options]
  end
end

plugins/redmine_dmsf/app/views/my/blocks/_locked_documents.html.erb
<%
# encoding: utf-8
#
# Redmine plugin for Document Management System "Features"
#
# Copyright © 2011-22 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<% folders = DmsfFolder.visible.joins(
  'JOIN dmsf_locks ON dmsf_folders.id = dmsf_locks.entity_id').where(
  ['dmsf_locks.entity_type = ? AND dmsf_locks.user_id = ? AND (dmsf_locks.expires_at IS NULL OR dmsf_locks.expires_at > ?)',
   1, @user&.id, Time.current]) %>
<% files = DmsfFile.visible.joins(
  'JOIN dmsf_locks ON dmsf_files.id = dmsf_locks.entity_id').where(
  ['dmsf_locks.entity_type = ? AND dmsf_locks.user_id = ? AND (dmsf_locks.expires_at IS NULL OR dmsf_locks.expires_at > ?)',
   0, @user&.id, Time.current]) %>
<h3><%= l(:locked_documents)%> (<%= folders.all.size %>/<%= files.all.size %>)</h3>
<% if folders.any? || files.any?%>
  <%= form_tag({}, data: { cm_url: dmsf_context_menu_path(back_url: my_page_path) }) do %>
    <table class="list context-menu-container" data-hascontextmenu="true">
      <thead>
        <tr>
          <th class="checkbox hide-when-print">
            <%= check_box_tag 'check_all', '', false, class: 'toggle-selection',
                              title: "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
          </th>
          <th><%= l(:field_project) %></th>
          <th><%= l(:label_document) %>/<%= l(:field_folder) %></th>
          <th><%= l(:field_folder) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% folders.each do |folder| %>
          <tr id="folder-<%= folder.id %>" class="hascontextmenu">
            <td class="checkbox hide-when-print">
              <%= check_box_tag 'ids[]', "folder-#{folder.id}", false, id: nil %>
            </td>
            <td class="project">
              <%= link_to_project folder.project %>
            </td>
            <td class="title">
              <%= link_to h(folder.title), dmsf_folder_path(id: folder.project, folder_id: folder),
                class: 'icon icon-folder' %>
             </td>
             <td class="title">
               <% if folder.dmsf_folder %>
                 <%= link_to h(folder.dmsf_folder.title),
                             dmsf_folder_path(id: folder.project, folder_id: folder.dmsf_folder) %>
               <% else %>
                  <%= link_to l(:link_documents), dmsf_folder_path(id: folder.project) %>
               <% end %>
             </td>
             <td>
               <%= link_to_context_menu %>
             </td>
           </tr>
        <% end %>
        <% files.each do |file| %>
          <tr id="file-<%= file.id %>" class="hascontextmenu">
            <td class="checkbox hide-when-print">
              <%= check_box_tag 'ids[]', "file-#{file.id}", false, id: nil %>
            </td>
            <td class="project">
              <%= link_to_project file.project %>
            </td>
            <td class="title">
              <%= link_to h(file.title), dmsf_file_path(id: file),
                class: "icon icon-file #{DmsfHelper.filetype_css(file.name)}" %>
            </td>
             <td class="title">
               <% if file.dmsf_folder %>
                 <%= link_to h(file.dmsf_folder.title), dmsf_folder_path(id: file.project, folder_id: file.dmsf_folder) %>
               <% else %>
                  <%= link_to_if file.project, l(:link_documents), dmsf_folder_path(id: file.project) %>
               <% end %>
             </td>
             <td>
               <%= link_to_context_menu %>
             </td>
           </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <%= context_menu %>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

plugins/redmine_dmsf/app/views/my/blocks/_open_approvals.html.erb
<%
# encoding: utf-8
#
# Redmine plugin for Document Management System "Features"
#
# Copyright © 2011-22 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<% all_assignments =  DmsfWorkflowStepAssignment.
      left_outer_joins(:dmsf_workflow_step_actions).
      joins(:dmsf_workflow_step).
      joins(:dmsf_file_revision).
      where(dmsf_file_revisions: { deleted: DmsfFileRevision::STATUS_ACTIVE, workflow: DmsfWorkflow::STATE_WAITING_FOR_APPROVAL }).
      where(dmsf_workflow_step_assignments: { user_id: @user&.id }).
      where(['dmsf_workflow_step_actions.id IS NULL OR dmsf_workflow_step_actions.action = ?',
       DmsfWorkflowStepAction::ACTION_DELEGATE]).
      order('dmsf_workflow_step_assignments.dmsf_file_revision_id, dmsf_workflow_steps.step').to_a %>
<% assignments = all_assignments.delete_if { |a| (a.dmsf_file_revision != a.dmsf_file_revision.dmsf_file.last_revision) } %>
<% assignments.uniq! { |a| a.dmsf_file_revision } %>
<h3><%= l(:open_approvals)%> (<%= assignments.size %>)</h3>
<% if assignments.any? %>
  <%= form_tag({}, data: { cm_url: dmsf_context_menu_path(back_url: my_page_path) }) do %>
    <table class="list">
      <thead>
        <tr>
          <th class="checkbox hide-when-print">
            <%= check_box_tag 'check_all', '', false, class: 'toggle-selection',
                              title: "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
          </th>
          <th><%= l(:field_project) %></th>
          <th><%= l(:field_label_dmsf_workflow) %></th>
          <th><%= l(:field_status) %></th>
          <th><%= l(:label_document) %></th>
          <th><%= l(:field_folder) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% assignments.each do |assignment| %>
          <tr id="file-<%= assignment.dmsf_file_revision.dmsf_file.id %>" class="hascontextmenu">
            <td class="checkbox hide-when-print">
              <%= check_box_tag 'ids[]', "file-#{assignment.dmsf_file_revision.dmsf_file.id}", false, id: nil %>
            </td>
            <td class="project">
              <% if assignment.dmsf_file_revision.dmsf_file.project %>
                <%= link_to_project assignment.dmsf_file_revision.dmsf_file.project %>
              <% end %>
            </td>
            <td>
              <% if assignment.dmsf_workflow_step && assignment.dmsf_workflow_step.dmsf_workflow %>
                  <%= link_to h(assignment.dmsf_workflow_step.dmsf_workflow.name),
                    edit_dmsf_workflow_path(assignment.dmsf_workflow_step.dmsf_workflow) %>
              <% end %>
            </td>
            <td class="dmsf_workflow">
              <% if assignment.dmsf_workflow_step.dmsf_workflow %>
                  <%= link_to assignment.dmsf_file_revision.workflow_str(false),
                          log_dmsf_workflow_path(
                              project_id: assignment.dmsf_file_revision.dmsf_file.project_id,
                              id: assignment.dmsf_workflow_step.dmsf_workflow_id,
                              dmsf_file_revision_id: assignment.dmsf_file_revision_id),
                          title: assignment.dmsf_file_revision.workflow_tooltip,
                          remote: true %>
              <% else %>
                  <%= assignment.dmsf_file_revision.workflow_str(false) %>
              <% end %>
            </td>
            <td class="title">
              <% if assignment.dmsf_file_revision && assignment.dmsf_file_revision.dmsf_file %>
                <%= link_to h(assignment.dmsf_file_revision.title),
                            dmsf_file_path(id: assignment.dmsf_file_revision.dmsf_file) %>
              <% end %>
            </td>
            <td class="title">
              <% if assignment.dmsf_file_revision %>
                <% if assignment.dmsf_file_revision.dmsf_file.dmsf_folder %>
                  <%= link_to h(assignment.dmsf_file_revision.dmsf_file.dmsf_folder.title),
                        dmsf_folder_path(id: assignment.dmsf_file_revision.dmsf_file.project,
                        folder_id: assignment.dmsf_file_revision.dmsf_file.dmsf_folder) %>
                <% elsif assignment.dmsf_file_revision.dmsf_file.project %>
                  <%= link_to l(:link_documents), dmsf_folder_path(id: assignment.dmsf_file_revision.dmsf_file.project) %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to_context_menu %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <%= context_menu %>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

plugins/redmine_dmsf/app/views/my/blocks/_watched_documents.html.erb
<%
# encoding: utf-8
#
# Redmine plugin for Document Management System "Features"
#
# Copyright © 2011-22 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<% projects = Project.visible.has_module(:dmsf).joins(:watchers).where(
  :watchers => { watchable_type: 'Project', user_id: @user&.id }) %>
<% folders = DmsfFolder.visible(:dmsf).joins(:watchers).where(
  :watchers => { watchable_type: 'DmsfFolder', user_id: @user&.id }) %>
<% files = DmsfFile.visible.joins(:watchers).where(
  :watchers => { watchable_type: 'DmsfFile', user_id: @user&.id }) %>
<h3><%= l(:label_dmsf_watched)%> (<%= projects.all.size + folders.all.size %>/<%=  files.all.size %>)</h3>
<% if projects.any? || folders.any? || files.any? %>
  <%= form_tag({}, data: { cm_url: dmsf_context_menu_path(back_url: my_page_path) }) do %>
    <table class="list context-menu-container" data-hascontextmenu="true">
      <thead>
        <tr>
          <th class="checkbox hide-when-print">
            <%= check_box_tag 'check_all', '', false, class: 'toggle-selection',
                              title: "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
          </th>
          <th><%= l(:field_project) %></th>
          <th><%= l(:label_document) %>/<%= l(:field_folder) %></th>
          <th><%= l(:field_folder) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% projects.each do |project| %>
          <tr id="project-<%= project.id %>" class="hascontextmenu">
            <td class="checkbox hide-when-print">
              <%= check_box_tag 'ids[]', "project-#{project.id}", false, id: nil %>
            </td>
            <td class="project">
              <%= link_to_project project %>
            </td>
            <td class="title">
              <%= link_to_project project, jump: 'dmsf', class: 'project' %>
            </td>
            <td class="title"></td>
            <td>
              <%= link_to_context_menu %>
            </td>
          </tr>
        <% end %>
        <% folders.each do |folder| %>
          <tr id="folder-<%= folder.id %>" class="hascontextmenu">
            <td class="checkbox hide-when-print">
              <%= check_box_tag 'ids[]', "folder-#{folder.id}", false, id: nil %>
            </td>
            <td class="project">
              <%= link_to_project folder.project %>
            </td>
            <td class="title">
              <%= link_to h(folder.title), dmsf_folder_path(id: folder.project, folder_id: folder),
                          class: 'icon icon-folder' %>
             </td>
             <td class="title">
               <% if folder.dmsf_folder %>
                 <%= link_to h(folder.dmsf_folder.title), dmsf_folder_path(id: folder.project, folder_id:
                   folder.dmsf_folder) %>
               <% else %>
                  <%= link_to l(:link_documents), dmsf_folder_path(id: folder.project) %>
               <% end %>
             </td>
            <td>
              <%= link_to_context_menu %>
            </td>
           </tr>
        <% end %>
        <% files.each do |file| %>
          <tr id="file-<%= file.id %>" class="hascontextmenu">
            <td class="checkbox hide-when-print">
              <%= check_box_tag 'ids[]', "file-#{file.id}", false, id: nil %>
            </td>
            <td class="project">
              <%= link_to_project(file.project) if file.project %>
            </td>
            <td class="title">
              <%= link_to h(file.title), dmsf_file_path(id: file),
                class: "icon icon-file #{DmsfHelper.filetype_css(file.name)}" %>
            </td>
            <td class="title">
              <% if file.dmsf_folder %>
                <%= link_to h(file.dmsf_folder.title), dmsf_folder_path(id: file.project, folder_id: file.dmsf_folder) %>
              <% else %>
                <%= link_to l(:link_documents), dmsf_folder_path(id: file.project) %>
              <% end %>
            </td>
            <td>
              <%= link_to_context_menu %>
            </td>
           </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <%= context_menu %>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>